package com.wj.demo.domain.sqlserver;

import java.io.Serializable;
import java.util.Date;

public class JsgcLixianpiwen implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.BelongXiaQuCode
     *
     * @mbggenerated
     */
    private String belongxiaqucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.OperateUserName
     *
     * @mbggenerated
     */
    private String operateusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.OperateDate
     *
     * @mbggenerated
     */
    private Date operatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.Row_ID
     *
     * @mbggenerated
     */
    private Integer rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.YearFlag
     *
     * @mbggenerated
     */
    private String yearflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.RowGuid
     *
     * @mbggenerated
     */
    private String rowguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.BeiAnWenHao
     *
     * @mbggenerated
     */
    private String beianwenhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.BeiAnTitle
     *
     * @mbggenerated
     */
    private String beiantitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.BeiAnBuMen
     *
     * @mbggenerated
     */
    private String beianbumen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.LRR_Code
     *
     * @mbggenerated
     */
    private String lrrCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.LRR_Name
     *
     * @mbggenerated
     */
    private String lrrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.LRR_Date
     *
     * @mbggenerated
     */
    private Date lrrDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.LiXianDate
     *
     * @mbggenerated
     */
    private Date lixiandate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.XiaQuCode
     *
     * @mbggenerated
     */
    private String xiaqucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.LiXiangGuid
     *
     * @mbggenerated
     */
    private String lixiangguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.JianSheDwType
     *
     * @mbggenerated
     */
    private String jianshedwtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.PiWenScan_ContentType
     *
     * @mbggenerated
     */
    private String piwenscanContenttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.PiWenScan_FileName
     *
     * @mbggenerated
     */
    private String piwenscanFilename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.IsChaiFen
     *
     * @mbggenerated
     */
    private String ischaifen;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.IsSendWeb
     *
     * @mbggenerated
     */
    private String issendweb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.BuMenType
     *
     * @mbggenerated
     */
    private String bumentype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.IsIn
     *
     * @mbggenerated
     */
    private String isin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.SBR_UnitGuid
     *
     * @mbggenerated
     */
    private String sbrUnitguid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.SBR_Name
     *
     * @mbggenerated
     */
    private String sbrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.SBR_IDCard
     *
     * @mbggenerated
     */
    private String sbrIdcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.SBR_Tel
     *
     * @mbggenerated
     */
    private String sbrTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.SBR_Moblie
     *
     * @mbggenerated
     */
    private String sbrMoblie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.SBR_UnitName
     *
     * @mbggenerated
     */
    private String sbrUnitname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.LuRuType
     *
     * @mbggenerated
     */
    private String lurutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.BackReason
     *
     * @mbggenerated
     */
    private String backreason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.IsSecTuiSong
     *
     * @mbggenerated
     */
    private String issectuisong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.CemterBeiAnWenHao
     *
     * @mbggenerated
     */
    private String cemterbeianwenhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.IsGYZJFB
     *
     * @mbggenerated
     */
    private String isgyzjfb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JSGC_LiXianPiWen.PiWenScan
     *
     * @mbggenerated
     */
    private byte[] piwenscan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JSGC_LiXianPiWen
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.BelongXiaQuCode
     *
     * @return the value of JSGC_LiXianPiWen.BelongXiaQuCode
     *
     * @mbggenerated
     */
    public String getBelongxiaqucode() {
        return belongxiaqucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.BelongXiaQuCode
     *
     * @param belongxiaqucode the value for JSGC_LiXianPiWen.BelongXiaQuCode
     *
     * @mbggenerated
     */
    public void setBelongxiaqucode(String belongxiaqucode) {
        this.belongxiaqucode = belongxiaqucode == null ? null : belongxiaqucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.OperateUserName
     *
     * @return the value of JSGC_LiXianPiWen.OperateUserName
     *
     * @mbggenerated
     */
    public String getOperateusername() {
        return operateusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.OperateUserName
     *
     * @param operateusername the value for JSGC_LiXianPiWen.OperateUserName
     *
     * @mbggenerated
     */
    public void setOperateusername(String operateusername) {
        this.operateusername = operateusername == null ? null : operateusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.OperateDate
     *
     * @return the value of JSGC_LiXianPiWen.OperateDate
     *
     * @mbggenerated
     */
    public Date getOperatedate() {
        return operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.OperateDate
     *
     * @param operatedate the value for JSGC_LiXianPiWen.OperateDate
     *
     * @mbggenerated
     */
    public void setOperatedate(Date operatedate) {
        this.operatedate = operatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.Row_ID
     *
     * @return the value of JSGC_LiXianPiWen.Row_ID
     *
     * @mbggenerated
     */
    public Integer getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.Row_ID
     *
     * @param rowId the value for JSGC_LiXianPiWen.Row_ID
     *
     * @mbggenerated
     */
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.YearFlag
     *
     * @return the value of JSGC_LiXianPiWen.YearFlag
     *
     * @mbggenerated
     */
    public String getYearflag() {
        return yearflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.YearFlag
     *
     * @param yearflag the value for JSGC_LiXianPiWen.YearFlag
     *
     * @mbggenerated
     */
    public void setYearflag(String yearflag) {
        this.yearflag = yearflag == null ? null : yearflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.RowGuid
     *
     * @return the value of JSGC_LiXianPiWen.RowGuid
     *
     * @mbggenerated
     */
    public String getRowguid() {
        return rowguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.RowGuid
     *
     * @param rowguid the value for JSGC_LiXianPiWen.RowGuid
     *
     * @mbggenerated
     */
    public void setRowguid(String rowguid) {
        this.rowguid = rowguid == null ? null : rowguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.BeiAnWenHao
     *
     * @return the value of JSGC_LiXianPiWen.BeiAnWenHao
     *
     * @mbggenerated
     */
    public String getBeianwenhao() {
        return beianwenhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.BeiAnWenHao
     *
     * @param beianwenhao the value for JSGC_LiXianPiWen.BeiAnWenHao
     *
     * @mbggenerated
     */
    public void setBeianwenhao(String beianwenhao) {
        this.beianwenhao = beianwenhao == null ? null : beianwenhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.BeiAnTitle
     *
     * @return the value of JSGC_LiXianPiWen.BeiAnTitle
     *
     * @mbggenerated
     */
    public String getBeiantitle() {
        return beiantitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.BeiAnTitle
     *
     * @param beiantitle the value for JSGC_LiXianPiWen.BeiAnTitle
     *
     * @mbggenerated
     */
    public void setBeiantitle(String beiantitle) {
        this.beiantitle = beiantitle == null ? null : beiantitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.BeiAnBuMen
     *
     * @return the value of JSGC_LiXianPiWen.BeiAnBuMen
     *
     * @mbggenerated
     */
    public String getBeianbumen() {
        return beianbumen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.BeiAnBuMen
     *
     * @param beianbumen the value for JSGC_LiXianPiWen.BeiAnBuMen
     *
     * @mbggenerated
     */
    public void setBeianbumen(String beianbumen) {
        this.beianbumen = beianbumen == null ? null : beianbumen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.LRR_Code
     *
     * @return the value of JSGC_LiXianPiWen.LRR_Code
     *
     * @mbggenerated
     */
    public String getLrrCode() {
        return lrrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.LRR_Code
     *
     * @param lrrCode the value for JSGC_LiXianPiWen.LRR_Code
     *
     * @mbggenerated
     */
    public void setLrrCode(String lrrCode) {
        this.lrrCode = lrrCode == null ? null : lrrCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.LRR_Name
     *
     * @return the value of JSGC_LiXianPiWen.LRR_Name
     *
     * @mbggenerated
     */
    public String getLrrName() {
        return lrrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.LRR_Name
     *
     * @param lrrName the value for JSGC_LiXianPiWen.LRR_Name
     *
     * @mbggenerated
     */
    public void setLrrName(String lrrName) {
        this.lrrName = lrrName == null ? null : lrrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.LRR_Date
     *
     * @return the value of JSGC_LiXianPiWen.LRR_Date
     *
     * @mbggenerated
     */
    public Date getLrrDate() {
        return lrrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.LRR_Date
     *
     * @param lrrDate the value for JSGC_LiXianPiWen.LRR_Date
     *
     * @mbggenerated
     */
    public void setLrrDate(Date lrrDate) {
        this.lrrDate = lrrDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.LiXianDate
     *
     * @return the value of JSGC_LiXianPiWen.LiXianDate
     *
     * @mbggenerated
     */
    public Date getLixiandate() {
        return lixiandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.LiXianDate
     *
     * @param lixiandate the value for JSGC_LiXianPiWen.LiXianDate
     *
     * @mbggenerated
     */
    public void setLixiandate(Date lixiandate) {
        this.lixiandate = lixiandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.XiaQuCode
     *
     * @return the value of JSGC_LiXianPiWen.XiaQuCode
     *
     * @mbggenerated
     */
    public String getXiaqucode() {
        return xiaqucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.XiaQuCode
     *
     * @param xiaqucode the value for JSGC_LiXianPiWen.XiaQuCode
     *
     * @mbggenerated
     */
    public void setXiaqucode(String xiaqucode) {
        this.xiaqucode = xiaqucode == null ? null : xiaqucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.LiXiangGuid
     *
     * @return the value of JSGC_LiXianPiWen.LiXiangGuid
     *
     * @mbggenerated
     */
    public String getLixiangguid() {
        return lixiangguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.LiXiangGuid
     *
     * @param lixiangguid the value for JSGC_LiXianPiWen.LiXiangGuid
     *
     * @mbggenerated
     */
    public void setLixiangguid(String lixiangguid) {
        this.lixiangguid = lixiangguid == null ? null : lixiangguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.JianSheDwType
     *
     * @return the value of JSGC_LiXianPiWen.JianSheDwType
     *
     * @mbggenerated
     */
    public String getJianshedwtype() {
        return jianshedwtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.JianSheDwType
     *
     * @param jianshedwtype the value for JSGC_LiXianPiWen.JianSheDwType
     *
     * @mbggenerated
     */
    public void setJianshedwtype(String jianshedwtype) {
        this.jianshedwtype = jianshedwtype == null ? null : jianshedwtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.PiWenScan_ContentType
     *
     * @return the value of JSGC_LiXianPiWen.PiWenScan_ContentType
     *
     * @mbggenerated
     */
    public String getPiwenscanContenttype() {
        return piwenscanContenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.PiWenScan_ContentType
     *
     * @param piwenscanContenttype the value for JSGC_LiXianPiWen.PiWenScan_ContentType
     *
     * @mbggenerated
     */
    public void setPiwenscanContenttype(String piwenscanContenttype) {
        this.piwenscanContenttype = piwenscanContenttype == null ? null : piwenscanContenttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.PiWenScan_FileName
     *
     * @return the value of JSGC_LiXianPiWen.PiWenScan_FileName
     *
     * @mbggenerated
     */
    public String getPiwenscanFilename() {
        return piwenscanFilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.PiWenScan_FileName
     *
     * @param piwenscanFilename the value for JSGC_LiXianPiWen.PiWenScan_FileName
     *
     * @mbggenerated
     */
    public void setPiwenscanFilename(String piwenscanFilename) {
        this.piwenscanFilename = piwenscanFilename == null ? null : piwenscanFilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.IsChaiFen
     *
     * @return the value of JSGC_LiXianPiWen.IsChaiFen
     *
     * @mbggenerated
     */
    public String getIschaifen() {
        return ischaifen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.IsChaiFen
     *
     * @param ischaifen the value for JSGC_LiXianPiWen.IsChaiFen
     *
     * @mbggenerated
     */
    public void setIschaifen(String ischaifen) {
        this.ischaifen = ischaifen == null ? null : ischaifen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.IsSendWeb
     *
     * @return the value of JSGC_LiXianPiWen.IsSendWeb
     *
     * @mbggenerated
     */
    public String getIssendweb() {
        return issendweb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.IsSendWeb
     *
     * @param issendweb the value for JSGC_LiXianPiWen.IsSendWeb
     *
     * @mbggenerated
     */
    public void setIssendweb(String issendweb) {
        this.issendweb = issendweb == null ? null : issendweb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.BuMenType
     *
     * @return the value of JSGC_LiXianPiWen.BuMenType
     *
     * @mbggenerated
     */
    public String getBumentype() {
        return bumentype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.BuMenType
     *
     * @param bumentype the value for JSGC_LiXianPiWen.BuMenType
     *
     * @mbggenerated
     */
    public void setBumentype(String bumentype) {
        this.bumentype = bumentype == null ? null : bumentype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.IsIn
     *
     * @return the value of JSGC_LiXianPiWen.IsIn
     *
     * @mbggenerated
     */
    public String getIsin() {
        return isin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.IsIn
     *
     * @param isin the value for JSGC_LiXianPiWen.IsIn
     *
     * @mbggenerated
     */
    public void setIsin(String isin) {
        this.isin = isin == null ? null : isin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.SBR_UnitGuid
     *
     * @return the value of JSGC_LiXianPiWen.SBR_UnitGuid
     *
     * @mbggenerated
     */
    public String getSbrUnitguid() {
        return sbrUnitguid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.SBR_UnitGuid
     *
     * @param sbrUnitguid the value for JSGC_LiXianPiWen.SBR_UnitGuid
     *
     * @mbggenerated
     */
    public void setSbrUnitguid(String sbrUnitguid) {
        this.sbrUnitguid = sbrUnitguid == null ? null : sbrUnitguid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.SBR_Name
     *
     * @return the value of JSGC_LiXianPiWen.SBR_Name
     *
     * @mbggenerated
     */
    public String getSbrName() {
        return sbrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.SBR_Name
     *
     * @param sbrName the value for JSGC_LiXianPiWen.SBR_Name
     *
     * @mbggenerated
     */
    public void setSbrName(String sbrName) {
        this.sbrName = sbrName == null ? null : sbrName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.SBR_IDCard
     *
     * @return the value of JSGC_LiXianPiWen.SBR_IDCard
     *
     * @mbggenerated
     */
    public String getSbrIdcard() {
        return sbrIdcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.SBR_IDCard
     *
     * @param sbrIdcard the value for JSGC_LiXianPiWen.SBR_IDCard
     *
     * @mbggenerated
     */
    public void setSbrIdcard(String sbrIdcard) {
        this.sbrIdcard = sbrIdcard == null ? null : sbrIdcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.SBR_Tel
     *
     * @return the value of JSGC_LiXianPiWen.SBR_Tel
     *
     * @mbggenerated
     */
    public String getSbrTel() {
        return sbrTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.SBR_Tel
     *
     * @param sbrTel the value for JSGC_LiXianPiWen.SBR_Tel
     *
     * @mbggenerated
     */
    public void setSbrTel(String sbrTel) {
        this.sbrTel = sbrTel == null ? null : sbrTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.SBR_Moblie
     *
     * @return the value of JSGC_LiXianPiWen.SBR_Moblie
     *
     * @mbggenerated
     */
    public String getSbrMoblie() {
        return sbrMoblie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.SBR_Moblie
     *
     * @param sbrMoblie the value for JSGC_LiXianPiWen.SBR_Moblie
     *
     * @mbggenerated
     */
    public void setSbrMoblie(String sbrMoblie) {
        this.sbrMoblie = sbrMoblie == null ? null : sbrMoblie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.SBR_UnitName
     *
     * @return the value of JSGC_LiXianPiWen.SBR_UnitName
     *
     * @mbggenerated
     */
    public String getSbrUnitname() {
        return sbrUnitname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.SBR_UnitName
     *
     * @param sbrUnitname the value for JSGC_LiXianPiWen.SBR_UnitName
     *
     * @mbggenerated
     */
    public void setSbrUnitname(String sbrUnitname) {
        this.sbrUnitname = sbrUnitname == null ? null : sbrUnitname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.LuRuType
     *
     * @return the value of JSGC_LiXianPiWen.LuRuType
     *
     * @mbggenerated
     */
    public String getLurutype() {
        return lurutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.LuRuType
     *
     * @param lurutype the value for JSGC_LiXianPiWen.LuRuType
     *
     * @mbggenerated
     */
    public void setLurutype(String lurutype) {
        this.lurutype = lurutype == null ? null : lurutype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.BackReason
     *
     * @return the value of JSGC_LiXianPiWen.BackReason
     *
     * @mbggenerated
     */
    public String getBackreason() {
        return backreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.BackReason
     *
     * @param backreason the value for JSGC_LiXianPiWen.BackReason
     *
     * @mbggenerated
     */
    public void setBackreason(String backreason) {
        this.backreason = backreason == null ? null : backreason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.IsSecTuiSong
     *
     * @return the value of JSGC_LiXianPiWen.IsSecTuiSong
     *
     * @mbggenerated
     */
    public String getIssectuisong() {
        return issectuisong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.IsSecTuiSong
     *
     * @param issectuisong the value for JSGC_LiXianPiWen.IsSecTuiSong
     *
     * @mbggenerated
     */
    public void setIssectuisong(String issectuisong) {
        this.issectuisong = issectuisong == null ? null : issectuisong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.CemterBeiAnWenHao
     *
     * @return the value of JSGC_LiXianPiWen.CemterBeiAnWenHao
     *
     * @mbggenerated
     */
    public String getCemterbeianwenhao() {
        return cemterbeianwenhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.CemterBeiAnWenHao
     *
     * @param cemterbeianwenhao the value for JSGC_LiXianPiWen.CemterBeiAnWenHao
     *
     * @mbggenerated
     */
    public void setCemterbeianwenhao(String cemterbeianwenhao) {
        this.cemterbeianwenhao = cemterbeianwenhao == null ? null : cemterbeianwenhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.IsGYZJFB
     *
     * @return the value of JSGC_LiXianPiWen.IsGYZJFB
     *
     * @mbggenerated
     */
    public String getIsgyzjfb() {
        return isgyzjfb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.IsGYZJFB
     *
     * @param isgyzjfb the value for JSGC_LiXianPiWen.IsGYZJFB
     *
     * @mbggenerated
     */
    public void setIsgyzjfb(String isgyzjfb) {
        this.isgyzjfb = isgyzjfb == null ? null : isgyzjfb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JSGC_LiXianPiWen.PiWenScan
     *
     * @return the value of JSGC_LiXianPiWen.PiWenScan
     *
     * @mbggenerated
     */
    public byte[] getPiwenscan() {
        return piwenscan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JSGC_LiXianPiWen.PiWenScan
     *
     * @param piwenscan the value for JSGC_LiXianPiWen.PiWenScan
     *
     * @mbggenerated
     */
    public void setPiwenscan(byte[] piwenscan) {
        this.piwenscan = piwenscan;
    }
}
